# Project
sonar.projectKey=NotesHub
sonar.projectName=NotesHub Backend
sonar.projectVersion=1.0

# SonarQube Server
sonar.host.url=http://localhost:9000

# Source
sonar.sources=src

# Tests
sonar.tests=tests

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8

# Ignore generated and dependency files
sonar.exclusions=node_modules/**,dist/**,coverage/**